extends RefCounted
const FONT = preload("res://assets/fonts/ui_font.tres")
var language: String = "ko"
const KO: Dictionary = {
 "RELEASE CONTROLS": "조작키를 놓아주세요",
 "Aim now; held wire input fires when the countdown ends.": "미리 조준하세요. 누른 와이어 입력은 카운트다운 종료 시 발사됩니다.",
 "ARMOR HIT — keep moving / protected for 2 seconds": "방어구 소모 — 그대로 진행 / 2초간 장애물 무적",
 "Keep moving after a hit: blink and ignore obstacles for 2s. Hidden while armor remains.": "충돌해도 그대로 진행하며 2초간 점멸·장애물 무적. 보유 중에는 선택지에서 제외됩니다.",
 "MANUAL SINGLE WIRE + E TWIN LAUNCH": "수동 한 줄 / E 두 줄 사출",
 "LAUNCH": "두 줄 사출",
 "TWIN LAUNCH": "두 줄 사출 강화",
 "E: dash toward two forward wall anchors. Speed upgrade; no invulnerability. 10s cooldown.": "E로 양쪽 벽의 중간 방향에 돌진. 속도 강화 / 무적 없음 / 재사용 10초.",
 "E: two forward walls required. 10s cooldown. No invulnerability.": "E: 전방 양쪽 벽이 필요합니다. 재사용 10초 / 무적 없음.",
 "TWIN LAUNCH COOLING DOWN": "두 줄 사출 재사용 대기 중",
 "TWIN LAUNCH NEEDS TWO FORWARD WALLS": "두 줄 사출: 전방 양쪽에 연결 가능한 건물이 필요합니다",
 "TWIN LAUNCH — collisions remain dangerous": "두 줄 사출 — 돌진 중에도 충돌하면 위험합니다",
 "ROUTE TEST / APPLIES NEXT RUN": "배치 비교 / 다음 시작부터 적용",
 "STANDARD": "기존 배치",
 "SPARSE BUILDINGS": "A: 건물 간격",
 "VERTICAL BARRIERS": "B: 수직 차단벽",
 "ROUTE / %s": "배치 / %s",
 "ROUTE TEST / NO RECORD": "배치 비교 / 최고 기록 제외",
 "E / READY": "E / 사출 준비",
 "E / TWO WALLS NEEDED": "E / 전방 양쪽 건물 필요",
 "E / %.1f s": "E / 재사용 %.1f초",
 "Language and next route are saved automatically.": "언어와 다음 배치가 자동 저장됩니다. 비교 배치는 기존 최고 기록에 반영되지 않습니다.",
 "LEFT CLOSED > RIGHT WALL": "왼쪽 차단 > 오른쪽 벽",
 "RIGHT CLOSED > LEFT WALL": "오른쪽 차단 > 왼쪽 벽",
 "RESUME SHIELD — protected for 2 seconds": "복귀 후 2초간 장애물 보호 — 5m 초과 해제의 착지 판정은 유지",
 "START RUN   /   ENTER": "기록 도전   /   ENTER",
 "PRACTICE   /   P": "연습 모드   /   P",
 "QUIT": "종료",
 "SETTINGS": "설정",
 "BACK   /   ESC": "뒤로   /   ESC",
 "LANGUAGE": "언어",
 "Settings could not be saved. They apply for this session.": "설정을 저장하지 못했습니다. 이번 실행에만 적용됩니다.",
 "RUN AGAIN   /   R": "다시 도전   /   R",
 "MAIN MENU": "메인 메뉴",
 "RESUME   /   ESC": "계속하기   /   ESC",
 "Find your rhythm above the city.": "도시 위에서 나만의 스윙을 만드세요.",
 "HOOK  >  SWING  >  RELEASE": "연결  >  스윙  >  해제",
 "SLIDE  >  JUMP  >  RECONNECT": "슬라이드  >  점프  >  재연결",
 "Best distance  %04d m": "최고 거리  %04d m",
 "YOUR FIRST SWING": "첫 스윙 안내",
 "Hold the mouse button to reel and climb automatically.": "마우스 버튼을 유지하면 자동으로 줄을 감습니다.",
 "PRACTICE / AUTO RESCUE": "연습 모드 / 자동 복구",
 "DISTANCE / PERSONAL BEST": "진행 거리 / 최고 기록",
 "SPEED": "속도",
 "GROUND": "지상 정지",
 "AIR": "공중",
 "SWING": "스윙",
 "SLIDE": "스케이트",
 "DEAD": "종료",
 "LV %02d   /   %d XP": "레벨 %02d   /   경험치 %d",
 "SKATES  %d   /   ARMOR  %d": "스케이트 %d   /   방어구 %d",
 "SKATE LANDINGS  %d": "스케이트 착지  %d회",
 "TAKE A BREATH": "잠시 쉬어 가세요",
 "RUN COMPLETE": "이번 도전 결과",
 "Top speed  %.1f m/s   /   Blocks  %d": "최고 속도 %.1f m/s   /   통과 구간 %d",
 "Skate landings  %d   /   Level  %d": "스케이트 착지 %d회   /   레벨 %d",
 "CHOOSE YOUR NEXT EDGE": "다음 능력을 선택하세요",
 "Level %d  /  physics and timers are paused": "레벨 %d  /  이동과 재사용 시간이 정지되었습니다",
 "READY  /  %d": "준비  /  %d",
 "Release all gameplay buttons to continue": "조작 버튼을 모두 놓으면 다시 시작합니다",
 "ROLLER SKATES": "롤러스케이트",
 "IMPACT ARMOR": "충격 방어구",
 "LONGER WIRE": "긴 와이어",
 "FAST REEL": "빠른 줄 감기",
 "FAST HOOK": "빠른 갈고리",
 "HIGH JUMP": "높은 점프",
 "+15% automatic reel speed while holding the mouse button.": "자동 줄 감기 속도 +15%. 버튼 유지로 스윙 반경을 줄입니다.",
 "+20% hook speed. Recover sooner after firing.": "갈고리 속도 +20%. 더 빨리 연결해 추락을 피하세요.",
 "MANUAL HOOK FIRED — position locked until the next shot": "직접 연결 — 다음 발사 전까지 선택한 지점을 유지합니다",
 "WIRE BLOCKED — disconnected": "줄 경로가 막혀 연결이 해제되었습니다",
 "ARMOR SAVED YOU": "방어구가 충돌을 막았습니다",
 "PRACTICE RESCUE": "연습 모드 자동 복구",
 "MISSED THE ROAD": "도로 밖으로 추락",
 "AIM AT A BUILDING": "건물 벽을 조준하세요",
 "OUT OF RANGE": "사거리 초과",
 "RANGE ASSIST": "사거리 내 표면으로 보정",
 "NO SURFACE IN RANGE": "사거리 안에 연결할 표면이 없습니다",
 "WIRE PATH BLOCKED": "줄 경로가 막혔습니다",
 "POINT READY": "연결 가능한 지점",
 "FREE FLOW": "자유 스윙",
 "MANUAL SINGLE WIRE": "수동 조준 / 와이어 1개",
 "Point at a wall or aerial obstacle; hold either mouse button.": "건물이나 공중 장애물을 가리키고 마우스 버튼을 유지하세요.",
 "Other button replaces wire. Far aim adjusts to wire reach.": "반대 버튼으로 연결점 교체. 먼 조준은 사거리 안으로 보정합니다.",
 "Release with player height at 5m or below: safe landing.": "줄을 놓는 순간 플레이어 높이 5m 이하: 안전 착지",
 "Release above 5m: fatal road landing, even with armor.": "플레이어 높이 5m 초과에서 해제: 착지 시 게임오버",
 "Unhooked jumps are exempt. Jumping alone does not renew skating.": "와이어 없는 점프는 예외. 점프만으로 스케이트는 갱신되지 않습니다.",
 "Skates reduce friction. Taller buildings also raise aerial obstacles.": "스케이트는 마찰 감소. 건물이 높아지면 공중 장애물도 올라갑니다.",
 "Language is saved automatically.": "언어 설정은 자동 저장됩니다.",
 "PROTOTYPE 06  /  GODOT 4": "프로토타입 06  /  GODOT 4",
 "Point at a wall or aerial obstacle to hook there.": "건물이나 공중 장애물의 원하는 지점을 조준하세요.",
 "Release the wire when your height is 5m or below.": "플레이어 높이가 5m 이하일 때 줄을 놓으세요.",
 "Practice: skates included; releasing above 5m risks a fatal landing.": "연습: 스케이트 제공. 5m 초과에서 놓으면 착지 위험.",
 "BUILDING HEIGHT  +%d m": "건물 높이  +%d m",
 " / TARGET %.1fm": " / 지점 높이 %.1fm",
 "JUMP LANDING EXEMPT": "일반 점프 — 착지 높이 판정 예외",
 "PLAYER %.2fm / RELEASE NOW %s": "현재 높이 %.2fm / 지금 놓으면 %s",
 "LAST RELEASE %.2fm / LANDING %s": "해제 당시 %.2fm / 착지 %s",
 "SAFE": "안전",
 "FATAL": "위험",
 "OBSTACLE SHIELD / %.1f s": "장애물 보호 / %.1f초",
 "FRICTION %.2f / %.1f m/s": "마찰 %.2f / %.1f m/s",
 "HOLD LMB / RMB  hook + reel     SPACE  jump     E  twin launch     A / D  steer     ESC  pause     R  restart": "좌·우 클릭 유지  수동 연결 + 줄 감기     SPACE  점프     E  두 줄 사출     A / D  조향     ESC  일시정지     R  재시작",
 "Skates %d / Armor %d / Buildings %d": "스케이트 %d / 방어구 %d / 건물 %d",
 "Lower ground friction each tier: 0.35 / 0.22 / 0.12. Release at player height 5m or below to slide.": "마찰 계수 0.35 / 0.22 / 0.12. 플레이어 높이 5m 이하에서 줄을 놓고 착지하면 슬라이드.",
 "Absorb an obstacle collision. Cannot save a landing after release above 5m.": "장애물 충돌을 1회 막습니다. 5m 초과에서 줄을 놓은 뒤 착지는 보호하지 않습니다.",
 "TALLER BUILDINGS": "높은 건물",
 "Raise buildings by 10 / 20 / 30m. Aerial obstacles also rise.": "건물 높이 +10 / 20 / 30m. 공중 장애물도 함께 높아집니다.",
 "+10% wire reach. Connect to a more distant point.": "와이어 사거리 +10%. 더 먼 지점에 연결합니다.",
 "+10% jump height. Unhooked jumps are safe to land.": "점프 높이 +10%. 연결하지 않은 일반 점프는 안전 착지.",
 "HOOK WALLS OR AERIAL OBSTACLES — release at player height 5m or below": "건물·공중 장애물에 연결 — 플레이어 높이 5m 이하에서 줄을 놓으세요",
 "AIM AT A SURFACE": "건물이나 공중 장애물을 조준하세요",
 "AIM ABOVE 2.5m": "높이 2.5m 이상 지점을 조준하세요",
 "JUMP — safe landing unless you connect a new wire": "점프 착지 예외 — 와이어를 새로 연결하면 예외가 해제됩니다",
 "HIGH RELEASE LANDING — player released above 5m": "착지 실패 — 줄을 놓을 때 플레이어 높이가 5m를 넘었습니다",
 "SKATING — friction slows you down; reconnect before landing again": "스케이트 — 마찰로 감속 / 재연결 후 플레이어 높이 5m 이하에서 놓으세요",
 "LANDED — stopped; Space to jump or mouse to hook": "착지 정지 — Space 점프 / 마우스로 다시 연결",
 "OBSTACLE COLLISION": "장애물 충돌",
 "SKY POSTS": "공중 기둥",
 "HIGH CROSSING": "상층 교차",
 "ZIGZAG": "엇갈린 장애물",
 "LOW APPROACH": "저공 접근",
 "AERIAL STEPS": "공중 계단"
}
func text(english: String) -> String:
 return str(KO.get(english, english)) if language == "ko" else english
func message(english: String) -> String:
 if language != "ko":
  return english
 if english.begins_with("PRACTICE RESCUE / "):
  return text("PRACTICE RESCUE") + " / " + message(english.trim_prefix("PRACTICE RESCUE / "))
 return text(english)
